import { bootstrapApplication } from '@angular/platform-browser';
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideRouter } from '@angular/router';
import { routes } from './app.routes';
import { authInterceptor } from './app/auth.interceptor';

export const apiUrl = 'http://localhost:3000/api';

@Component({ selector: 'app-navbar', standalone: true, template: `<header class="nav-wrap"><nav class="nav container" aria-label="Navegación principal"><a class="brand" href="#inicio" aria-label="Brújula inicio"><span class="brand-mark">✦</span><span>brújula</span></a><div class="nav-links"><a href="#beneficios">Beneficios</a><a href="#como-funciona">Cómo funciona</a><a href="#contacto">Preguntas frecuentes</a></div><a class="nav-button" href="#comenzar">Comenzar gratis <span>↗</span></a><button class="menu" aria-label="Abrir menú">☰</button></nav></header>` })
export class NavbarComponent {}

@Component({ selector: 'app-hero', standalone: true, template: `<section class="hero" id="inicio"><div class="container hero-grid"><div class="hero-copy"><div class="eyebrow"><span></span> TU TIEMPO, A TU FAVOR</div><h1>Estudia con rumbo.<br><em>Vive con calma.</em></h1><p>Brújula te ayuda a organizar tus horas de estudio, cuidar tus descansos y llegar a todo sin sentir que vas tarde.</p><div class="hero-actions"><a href="#comenzar" class="button primary">Crear mi horario <span>→</span></a><a href="#como-funciona" class="watch"><span class="play">▶</span> Mira cómo funciona</a></div><div class="proof"><div class="avatars"><span>LM</span><span>SC</span><span>JP</span><b>+2k</b></div><span>Estudiantes que ya<br><strong>encontraron su ritmo</strong></span></div></div><div class="hero-visual" aria-label="Vista previa del horario de estudio"><div class="blob"></div><div class="schedule-card"><div class="card-top"><div><small>MI SEMANA</small><h3>Hola, Alex <span>✦</span></h3></div><div class="sun">☀</div></div><div class="week"><span>LUN<strong>12</strong></span><span class="active">MAR<strong>13</strong></span><span>MIÉ<strong>14</strong></span><span>JUE<strong>15</strong></span><span>VIE<strong>16</strong></span></div><div class="timeline"><div class="time">09:00</div><div class="event blue"><b>Repaso de cálculo</b><small>09:00 — 10:30 · Biblioteca</small></div><div class="time">11:00</div><div class="event green"><b>Descanso consciente</b><small>11:00 — 11:30 · Pausa</small></div><div class="time">13:00</div><div class="event peach"><b>Almuerzo</b><small>13:00 — 14:00 · Sin pantallas</small></div></div><div class="progress"><span>Tu foco de hoy</span><strong>72%</strong><div><i></i></div></div></div><div class="float-note"><span>✓</span><div><b>¡Buen ritmo!</b><small>3 días de constancia</small></div></div></div></div></section>` })
export class HeroComponent {}

@Component({ selector: 'app-features', standalone: true, template: `<section class="section features" id="beneficios"><div class="container"><div class="section-heading"><div><div class="eyebrow">TODO EN UN SOLO LUGAR</div><h2>Menos ruido.<br><em>Más claridad.</em></h2></div><p>Tu vida universitaria ya es bastante intensa. Brújula convierte el caos de pendientes en un plan que sí puedes disfrutar.</p></div><div class="feature-grid"><article class="feature-card blue-card"><span class="icon">◫</span><h3>Planifica sin complicarte</h3><p>Organiza clases, entregas y sesiones de estudio en minutos.</p><a href="#como-funciona">Conoce más <span>↗</span></a></article><article class="feature-card green-card"><span class="icon">◒</span><h3>Cuida tu energía</h3><p>Incluye pausas reales y encuentra un ritmo sostenible para ti.</p><a href="#como-funciona">Conoce más <span>↗</span></a></article><article class="feature-card peach-card"><span class="icon">⌁</span><h3>Avanza a tu manera</h3><p>Visualiza tus pequeños logros y mantén la motivación en el camino.</p><a href="#comenzar">Conoce más <span>↗</span></a></article></div></div></section>` })
export class FeaturesComponent {}

@Component({ selector: 'app-how-it-works', standalone: true, template: `<section class="section how" id="como-funciona"><div class="container how-grid"><div class="phone"><div class="phone-notch"></div><div class="phone-head"><span>←</span><b>Tu enfoque</b><span>•••</span></div><div class="circle-progress"><strong>68%</strong><small>de tu meta</small></div><div class="focus-row"><span>◉</span><div><b>Bloque de estudio</b><small>Química orgánica</small></div><i>45 min</i></div><div class="focus-row"><span>✓</span><div><b>Descanso</b><small>Respira y recarga</small></div><i>15 min</i></div></div><div class="how-copy"><div class="eyebrow">UNA FORMA MÁS SIMPLE</div><h2>Tu día, <em>en tus manos.</em></h2><p>Empieza con lo que tienes. Brújula se adapta a tu realidad, no al revés.</p><div class="steps"><div><b>01</b><span><strong>Cuéntanos tu semana</strong><small>Agrega tus clases y compromisos fijos.</small></span></div><div><b>02</b><span><strong>Define tus prioridades</strong><small>Elige qué quieres lograr esta semana.</small></span></div><div><b>03</b><span><strong>Encuentra tu ritmo</strong><small>Recibe un horario posible y flexible.</small></span></div></div></div></div></section>` })
export class HowItWorksComponent {}

@Component({ selector: 'app-cta', standalone: true, template: `<section class="cta" id="comenzar"><div class="container cta-inner"><div><div class="eyebrow">EMPIEZA HOY</div><h2>Tu mejor semestre<br><em>empieza con un plan.</em></h2><p>Gratis para siempre. Sin tarjeta. A tu ritmo.</p></div><a class="button dark" href="#inicio">Crear mi horario <span>→</span></a></div></section>` }) export class CtaComponent {}
@Component({ selector: 'app-footer', standalone: true, template: `<footer id="contacto"><div class="container footer-top"><a class="brand" href="#inicio"><span class="brand-mark">✦</span><span>brújula</span></a><span>Hecho para estudiantes que quieren llegar lejos<br>sin olvidarse de disfrutar el camino.</span><div class="socials"><a href="#inicio" aria-label="Instagram">ig</a><a href="#inicio" aria-label="Twitter">tw</a><a href="#inicio" aria-label="LinkedIn">in</a></div></div><div class="container footer-bottom"><span>© 2024 Brújula. Hecho con calma.</span><span><a href="#inicio">Privacidad</a> &nbsp; <a href="#inicio">Términos</a></span></div></footer>` }) export class FooterComponent {}

@Component({ selector: 'app-root', standalone: true, imports: [CommonModule, NavbarComponent, HeroComponent, FeaturesComponent, HowItWorksComponent, CtaComponent, FooterComponent], template: `<app-navbar/><main><app-hero/><app-features/><app-how-it-works/><app-cta/></main><app-footer/>` })
export class AppComponent {}

bootstrapApplication(AppComponent, {
  providers: [provideRouter(routes), provideHttpClient(withInterceptors([authInterceptor]))],
}).catch(err => console.error(err));
